Sprint 2

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

#connects to our shared google drive folder that has the csv. Professor I have added you to the shared drive so you can run the code
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = '/content/drive/Shareddrives/CS122 Group 12/train.csv'
df= pd.read_csv(path)
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [ ]:
df.dtypes

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [ ]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [ ]:
df = df.dropna()
print(df.head())
df.isnull().sum()

   Unnamed: 0                track_id                 artists  \
0           0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino
1           1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward
2           2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN
3           3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis
4           4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet

                                          album_name  \
0                                             Comedy
1                                   Ghost (Acoustic)
2                                     To Begin Again
3  Crazy Rich Asians (Original Motion Picture Sou...
4                                            Hold On

                   track_name  popularity  duration_ms  explicit  \
0                      Comedy          73       230666     False
1            Ghost - Acoustic          55       149610     False
2              To Begin Again          57       210826     False
3  Can't Help Falling In Love          71       201933     False
4                     Hold On          82       198853     False

   danceability  energy  ...  loudness  mode  speechiness  acousticness  \
0         0.676  0.4610  ...    -6.746     0       0.1430        0.0322
1         0.420  0.1660  ...   -17.235     1       0.0763        0.9240
2         0.438  0.3590  ...    -9.734     1       0.0557        0.2100
3         0.266  0.0596  ...   -18.515     1       0.0363        0.9050
4         0.618  0.4430  ...    -9.681     1       0.0526        0.4690

   instrumentalness  liveness  valence    tempo  time_signature  track_genre
0          0.000001    0.3580    0.715   87.917               4     acoustic
1          0.000006    0.1010    0.267   77.489               4     acoustic
2          0.000000    0.1170    0.120   76.332               4     acoustic
3          0.000071    0.1320    0.143  181.740               3     acoustic
4          0.000000    0.0829    0.167  119.949               4     acoustic

[5 rows x 21 columns]

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [ ]:
#Determine popularity columns range
print(df['popularity'].min())
print(df['popularity'].max())

0
100

In [ ]:
#Create a row based off different ranges of popularity to assign a general ranking for later data analysis use
#Ranges include Popular: 100 - 70, Average: 69 - 40, Unpopular: 39-0
#Feel free to expand on this later if we need more robust categories

def pop_assign(score):
  if score >= 70:
    return 'Popular'
  elif score >= 40:
    return 'Average'
  else:
    return 'Unpopular'

#changing the column names
#popularity rating is now the raw popularity score
df = df.rename(columns={'popularity': 'popularity rating'})

#popularity will not be the column for the assigned values
df['popularity'] = df['popularity rating'].map(pop_assign)
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity rating,duration_ms,explicit,danceability,energy,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,popularity
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic,Popular
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic,Average
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic,Average
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic,Popular
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic,Popular

In [ ]:
df = df[df['popularity rating'] != 0]  # drop columns where popularity rating is 0

features_to_keep = [
    'duration_ms', 'explicit',
    'danceability', 'energy', 'key', 'loudness',
    'speechiness', 'acousticness', 'instrumentalness',
    'liveness', 'valence', 'tempo', 'time_signature',
    'track_genre'
]
#prediction_feature = 'popularity rating'

X_unprocessed = df[features_to_keep]
y = df['mode'] #to classify the mode (0 or 1)

X_unprocessed.dtypes  # from the output, need to change explicit (bool to int) and track_genre (one hot encoding for categorical variable)

duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

categorical_cols = ['track_genre']
binary_cols = ['explicit']
numeric_cols = [col for col in X_unprocessed.columns if col not in categorical_cols + binary_cols]

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('bin', 'passthrough', binary_cols),
        ('num', StandardScaler(), numeric_cols)
    ]
)

X = preprocessor.fit_transform(X_unprocessed)
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1282182 stored elements and shape (97980, 127)>

#ML Modeling

In [ ]:
print(df['mode'].value_counts())

mode
1    62169
0    35811
Name: count, dtype: int64

In [ ]:
#imports
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier, HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
#train test splits - 80/20
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

### Creating model 1: linear regression model

In [ ]:
lr = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

#eval
print("Logistic Regression evaluation metrics:")
print(classification_report(y_test,y_pred_lr))

Logistic Regression evaluation metrics:
              precision    recall  f1-score   support

           0       0.47      0.66      0.55      7028
           1       0.76      0.59      0.66     12568

    accuracy                           0.61     19596
   macro avg       0.61      0.62      0.61     19596
weighted avg       0.65      0.61      0.62     19596

### Model 2: Random Forest (best results for mode classification)

In [ ]:
rf = RandomForestClassifier(n_estimators=50, class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

#eval
print("Random Forest evaluation metrics:")
print(classification_report(y_test,y_pred_rf))

Random Forest evaluation metrics:
              precision    recall  f1-score   support

           0       0.77      0.56      0.65      7028
           1       0.79      0.91      0.84     12568

    accuracy                           0.78     19596
   macro avg       0.78      0.73      0.75     19596
weighted avg       0.78      0.78      0.77     19596

###Model 3: Gradient Boosting

In [ ]:
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

#eval
print("Gradient Boosting evaluation metrics:")
print(classification_report(y_test,y_pred_gb))

Gradient Boosting evaluation metrics:
              precision    recall  f1-score   support

           0       0.65      0.35      0.46      7028
           1       0.71      0.90      0.79     12568

    accuracy                           0.70     19596
   macro avg       0.68      0.62      0.62     19596
weighted avg       0.69      0.70      0.67     19596